PC_DISPLAY_NAMES = ("Computer", "This PC")
DCIM_NAME = "DCIM"
INTERNAL_STORAGE_NAME = "Internal Storage"

INDEX_NAME = "index.csv"
BACKUP_FILE_EXTENSION = ".backup"

DIFF_ADDED = "ADDED"
DIFF_MODIFIED = "MODIFIED"
DIFF_REMOVED = "REMOVED"

CONSOLE_CYAN = "\033[96m"
CONSOLE_GREEN = "\033[92m"
CONSOLE_RED = "\033[91m"
CONSOLE_END_COLOR = "\033[0m"

STEP_ONE_TEXT = "Indexing (Step 1/2)"
STEP_TWO_TEXT = "Synchronizing (Step 2/2)"

RC_OK = 0
RC_INVALID_ARGUMENT = 1
RC_NO_DEVICE_FOUND = 2
RC_NO_DEVICE_WITH_NAME = 3
RC_MISSING_INFO = 4
RC_INTERRUPTED = 5
RC_FAILED = 6

DEVICE_IPHONE = "iPhone"

FILE_SIZES = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
FILE_EMPTY = "0 B"
