PC_DISPLAY_NAMES = ("Computer", "This PC")
DCIM_NAME = "DCIM"
INTERNAL_STORAGE_NAME = "Internal Storage"
INDEX_NAME = "index.csv"
DIFF_ADDED = "+"
DIFF_MODIFIED = "~"
DIFF_REMOVED = "-"
BUFFER_SIZE = 4194304
